services:
  db:
    image: postgres:18-alpine
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    container_name: contract_clause_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "5432:5432"
    networks:
      - production_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    container_name: contract_clause_re
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "6379:6379"
    networks:
      - production_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
