"""reset db

Revision ID: 8e84f9bc4263
Revises: 
Create Date: 2026-08-21 09:07:44.617681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8e84f9bc4263'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'VIEWER', name='role'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('analysis',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('document_summary', sa.Text(), nullable=True),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('overall_risk_score', sa.Integer(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('report_stored', sa.Boolean(), nullable=False),
    sa.Column('report_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_report_task_id'), 'analysis', ['report_task_id'], unique=False)
    op.create_index(op.f('ix_analysis_task_id'), 'analysis', ['task_id'], unique=False)
    op.create_index(op.f('ix_analysis_title'), 'analysis', ['title'], unique=False)
    op.create_index(op.f('ix_analysis_user_id'), 'analysis', ['user_id'], unique=False)
    op.create_table('refreshtoken',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('last_used_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtoken_token_hash'), 'refreshtoken', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False)
    op.create_table('clause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'AVERAGE', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('key_terms', sa.JSON(), nullable=True),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clause')
    op.drop_index(op.f('ix_refreshtoken_user_id'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_token_hash'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    op.drop_index(op.f('ix_analysis_user_id'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_title'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_task_id'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_report_task_id'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_table('users')
    # ### end Alembic commands ###
